export interface DistrictInfo {
  nameEn: string;
  nameBn: string;
  isDhaka: boolean;
  division?: string;
}

export const BD_DISTRICTS: DistrictInfo[] = [
  { nameEn: "Dhaka", nameBn: "ঢাকা", isDhaka: true, division: "Dhaka" },
  { nameEn: "Chattogram", nameBn: "চট্টগ্রাম", isDhaka: false, division: "Chattogram" },
  { nameEn: "Gazipur", nameBn: "গাজীপুর", isDhaka: false, division: "Dhaka" },
  { nameEn: "Narayanganj", nameBn: "নারায়ণগঞ্জ", isDhaka: false, division: "Dhaka" },
  { nameEn: "Sylhet", nameBn: "সিলেট", isDhaka: false, division: "Sylhet" },
  { nameEn: "Rajshahi", nameBn: "রাজশাহী", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Khulna", nameBn: "খুলনা", isDhaka: false, division: "Khulna" },
  { nameEn: "Barishal", nameBn: "বরিশাল", isDhaka: false, division: "Barishal" },
  { nameEn: "Rangpur", nameBn: "রংপুর", isDhaka: false, division: "Rangpur" },
  { nameEn: "Mymensingh", nameBn: "ময়মনসিংহ", isDhaka: false, division: "Mymensingh" },
  { nameEn: "Cumilla", nameBn: "কুমিল্লা", isDhaka: false, division: "Chattogram" },
  { nameEn: "Bogura", nameBn: "বগুড়া", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Cox's Bazar", nameBn: "কক্সবাজার", isDhaka: false, division: "Chattogram" },
  { nameEn: "Narsingdi", nameBn: "নরসিংদী", isDhaka: false, division: "Dhaka" },
  { nameEn: "Tangail", nameBn: "টাঙ্গাইল", isDhaka: false, division: "Dhaka" },
  { nameEn: "Feni", nameBn: "ফেনী", isDhaka: false, division: "Chattogram" },
  { nameEn: "Noakhali", nameBn: "নোয়াখালী", isDhaka: false, division: "Chattogram" },
  { nameEn: "Brahmanbaria", nameBn: "ব্রাহ্মণবাড়িয়া", isDhaka: false, division: "Chattogram" },
  { nameEn: "Chandpur", nameBn: "চাঁদপুর", isDhaka: false, division: "Chattogram" },
  { nameEn: "Jashore", nameBn: "যশোর", isDhaka: false, division: "Khulna" },
  { nameEn: "Kushtia", nameBn: "কুষ্টিয়া", isDhaka: false, division: "Khulna" },
  { nameEn: "Pabna", nameBn: "পাবনা", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Dinajpur", nameBn: "দিনাজপুর", isDhaka: false, division: "Rangpur" },
  { nameEn: "Faridpur", nameBn: "ফরিদপুর", isDhaka: false, division: "Dhaka" },
  { nameEn: "Bagerhat", nameBn: "বাগেরহাট", isDhaka: false, division: "Khulna" },
  { nameEn: "Bandarban", nameBn: "বান্দরবান", isDhaka: false, division: "Chattogram" },
  { nameEn: "Barguna", nameBn: "বরগুনা", isDhaka: false, division: "Barishal" },
  { nameEn: "Bhola", nameBn: "ভোলা", isDhaka: false, division: "Barishal" },
  { nameEn: "Chapainawabganj", nameBn: "চাঁপাইনবাবগঞ্জ", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Chuadanga", nameBn: "চুয়াডাঙ্গা", isDhaka: false, division: "Khulna" },
  { nameEn: "Gaibandha", nameBn: "গাইবান্ধা", isDhaka: false, division: "Rangpur" },
  { nameEn: "Gopalganj", nameBn: "গোপালগঞ্জ", isDhaka: false, division: "Dhaka" },
  { nameEn: "Habiganj", nameBn: "হবিগঞ্জ", isDhaka: false, division: "Sylhet" },
  { nameEn: "Jamalpur", nameBn: "জামালপুর", isDhaka: false, division: "Mymensingh" },
  { nameEn: "Jhalokathi", nameBn: "ঝালকাঠি", isDhaka: false, division: "Barishal" },
  { nameEn: "Jhenaidah", nameBn: "ঝিনাইদহ", isDhaka: false, division: "Khulna" },
  { nameEn: "Joypurhat", nameBn: "জয়পুরহাট", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Khagrachhari", nameBn: "খাগড়াছড়ি", isDhaka: false, division: "Chattogram" },
  { nameEn: "Kishoreganj", nameBn: "কিশোরগঞ্জ", isDhaka: false, division: "Dhaka" },
  { nameEn: "Kurigram", nameBn: "কুড়িগ্রাম", isDhaka: false, division: "Rangpur" },
  { nameEn: "Lakshmipur", nameBn: "লক্ষ্মীপুর", isDhaka: false, division: "Chattogram" },
  { nameEn: "Lalmonirhat", nameBn: "লালমনিরহাট", isDhaka: false, division: "Rangpur" },
  { nameEn: "Madaripur", nameBn: "মাদারীপুর", isDhaka: false, division: "Dhaka" },
  { nameEn: "Magura", nameBn: "মাগুরা", isDhaka: false, division: "Khulna" },
  { nameEn: "Manikganj", nameBn: "মানিকগঞ্জ", isDhaka: false, division: "Dhaka" },
  { nameEn: "Meherpur", nameBn: "মেহেরপুর", isDhaka: false, division: "Khulna" },
  { nameEn: "Moulvibazar", nameBn: "মৌলভীবাজার", isDhaka: false, division: "Sylhet" },
  { nameEn: "Munshiganj", nameBn: "মুন্সীগঞ্জ", isDhaka: false, division: "Dhaka" },
  { nameEn: "Naogaon", nameBn: "নওগাঁ", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Narail", nameBn: "নড়াইল", isDhaka: false, division: "Khulna" },
  { nameEn: "Natore", nameBn: "নাটোর", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Netrokona", nameBn: "নেত্রকোণা", isDhaka: false, division: "Mymensingh" },
  { nameEn: "Nilphamari", nameBn: "নীলফামারী", isDhaka: false, division: "Rangpur" },
  { nameEn: "Panchagarh", nameBn: "পঞ্চগড়", isDhaka: false, division: "Rangpur" },
  { nameEn: "Patuakhali", nameBn: "পটুয়াখালী", isDhaka: false, division: "Barishal" },
  { nameEn: "Pirojpur", nameBn: "পিরোজপুর", isDhaka: false, division: "Barishal" },
  { nameEn: "Rajbari", nameBn: "রাজবাড়ী", isDhaka: false, division: "Dhaka" },
  { nameEn: "Rangamati", nameBn: "রাঙ্গামাটি", isDhaka: false, division: "Chattogram" },
  { nameEn: "Satkhira", nameBn: "সাতক্ষীরা", isDhaka: false, division: "Khulna" },
  { nameEn: "Shariatpur", nameBn: "শরীয়তপুর", isDhaka: false, division: "Dhaka" },
  { nameEn: "Sherpur", nameBn: "শেরপুর", isDhaka: false, division: "Mymensingh" },
  { nameEn: "Sirajganj", nameBn: "সিরাজগঞ্জ", isDhaka: false, division: "Rajshahi" },
  { nameEn: "Sunamganj", nameBn: "সুনামগঞ্জ", isDhaka: false, division: "Sylhet" },
  { nameEn: "Thakurgaon", nameBn: "ঠাকুরগাঁও", isDhaka: false, division: "Rangpur" },
];

export const bdDistricts = BD_DISTRICTS.map(d => d.nameEn);


